<?php

$files = [
// From v4.0.0 to v5.0.0
'/administrator/components/com_dpcalendar/controllers/send.php',
'/administrator/components/com_dpcalendar/libraries/caldav/vendor',
'/administrator/components/com_dpcalendar/models/events.php',
'/administrator/components/com_dpcalendar/models/fields/color.php',
'/administrator/components/com_dpcalendar/views/attendee/tmpl/edit_25.php',
'/administrator/components/com_dpcalendar/views/attendee/tmpl/edit_3.php',
'/administrator/components/com_dpcalendar/views/attendees/tmpl/default_25.php',
'/administrator/components/com_dpcalendar/views/attendees/tmpl/default_3.php',
'/administrator/components/com_dpcalendar/views/attendees/tmpl/modal_25.php',
'/administrator/components/com_dpcalendar/views/attendees/tmpl/modal_3.php',
'/administrator/components/com_dpcalendar/views/cpanel/tmpl/default_25.php',
'/administrator/components/com_dpcalendar/views/cpanel/tmpl/default_3.css',
'/administrator/components/com_dpcalendar/views/cpanel/tmpl/default_3.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_25.js',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_25.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_25_attend.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_25_date.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_25_metadata.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_25_params.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_3.js',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_3.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_3_attend.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_3_date.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_3_metadata.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_3_params.php',
'/administrator/components/com_dpcalendar/views/event/tmpl/edit_3_payment.php',
'/administrator/components/com_dpcalendar/views/events/tmpl/default_25.php',
'/administrator/components/com_dpcalendar/views/events/tmpl/default_25_batch.php',
'/administrator/components/com_dpcalendar/views/events/tmpl/default_3.php',
'/administrator/components/com_dpcalendar/views/events/tmpl/default_3_batch.php',
'/administrator/components/com_dpcalendar/views/events/tmpl/modal_25.php',
'/administrator/components/com_dpcalendar/views/events/tmpl/modal_3.php',
'/administrator/components/com_dpcalendar/views/location/tmpl/edit_25.php',
'/administrator/components/com_dpcalendar/views/location/tmpl/edit_25_params.php',
'/administrator/components/com_dpcalendar/views/location/tmpl/edit_3.php',
'/administrator/components/com_dpcalendar/views/location/tmpl/edit_3_params.php',
'/administrator/components/com_dpcalendar/views/locations/tmpl/default_25.php',
'/administrator/components/com_dpcalendar/views/locations/tmpl/default_25_batch.php',
'/administrator/components/com_dpcalendar/views/locations/tmpl/default_3.php',
'/administrator/components/com_dpcalendar/views/locations/tmpl/default_3_batch.php',
'/administrator/components/com_dpcalendar/views/support/tmpl/default_25.php',
'/administrator/components/com_dpcalendar/views/support/tmpl/default_3.php',
'/administrator/components/com_dpcalendar/views/tools/tmpl/default_25.php',
'/administrator/components/com_dpcalendar/views/tools/tmpl/default_3.php',
'/administrator/components/com_dpcalendar/views/tools/tmpl/import_25.php',
'/administrator/components/com_dpcalendar/views/tools/tmpl/import_3.php',
'/components/com_dpcalendar/helpers/icon.php',
'/components/com_dpcalendar/libraries/jquery/ext/chosen-sprite.png',
'/components/com_dpcalendar/libraries/jquery/ext/jquery.ba-hashchange.min.js',
'/components/com_dpcalendar/libraries/jquery/ext/jquery.chosen.css',
'/components/com_dpcalendar/libraries/jquery/ext/jquery.chosen.min.js',
'/components/com_dpcalendar/libraries/jquery/jquery.migrate.min.js',
'/components/com_dpcalendar/libraries/jquery/jquery.min.js',
'/components/com_dpcalendar/views/form/tmpl/edit_attend.php',
'/modules/mod_dpcalendar_mini/tmpl/dpcalendar.css',
'/plugins/dpcalendar/caldav/params.xml',
'/plugins/dpcalendar/csv/params.xml',
'/plugins/dpcalendar/exchange/params.xml',
'/plugins/dpcalendar/facebook/params.xml',
'/plugins/dpcalendar/google/params.xml',
'/plugins/dpcalendar/ical/params.xml',

// From v5.0.0 to v6.0.0
'/administrator/components/com_dpcalendar/controllers/attendee.php',
'/administrator/components/com_dpcalendar/controllers/attendees.php',
'/administrator/components/com_dpcalendar/controllers/index.html',
'/administrator/components/com_dpcalendar/helpers/ical.php',
'/administrator/components/com_dpcalendar/helpers/index.html',
'/administrator/components/com_dpcalendar/helpers/location.php',
'/administrator/components/com_dpcalendar/helpers/payment.php',
'/administrator/components/com_dpcalendar/helpers/schema.php',
'/administrator/components/com_dpcalendar/helpers/transifex.php',
'/administrator/components/com_dpcalendar/index.html',
'/administrator/components/com_dpcalendar/layouts',
'/administrator/components/com_dpcalendar/libraries/caldav',
'/administrator/components/com_dpcalendar/libraries/dpcalendar/index.html',
'/administrator/components/com_dpcalendar/libraries/dpcalendar/paymentplugin.php',
'/administrator/components/com_dpcalendar/libraries/dpcalendar/plugin.php',
'/administrator/components/com_dpcalendar/libraries/dpcalendar/view.php',
'/administrator/components/com_dpcalendar/libraries/iframe-resizer',
'/administrator/components/com_dpcalendar/libraries/index.html',
'/administrator/components/com_dpcalendar/libraries/jcomments/index.html',
'/administrator/components/com_dpcalendar/libraries/jscolor',
'/administrator/components/com_dpcalendar/libraries/mustache',
'/administrator/components/com_dpcalendar/models/attendee.php',
'/administrator/components/com_dpcalendar/models/attendees.php',
'/administrator/components/com_dpcalendar/models/event.php',
'/administrator/components/com_dpcalendar/models/fields/attendee.php',
'/administrator/components/com_dpcalendar/models/fields/index.html',
'/administrator/components/com_dpcalendar/models/forms/attendee.xml',
'/administrator/components/com_dpcalendar/models/forms/filter_payments.xml',
'/administrator/components/com_dpcalendar/models/forms/index.html',
'/administrator/components/com_dpcalendar/models/index.html',
'/administrator/components/com_dpcalendar/sql/index.html',
'/administrator/components/com_dpcalendar/tables/attendee.php',
'/administrator/components/com_dpcalendar/tables/index.html',
'/administrator/components/com_dpcalendar/views/attendee',
'/administrator/components/com_dpcalendar/views/attendees',
'/administrator/components/com_dpcalendar/views/cpanel/index.html',
'/administrator/components/com_dpcalendar/views/cpanel/tmpl/index.html',
'/administrator/components/com_dpcalendar/views/event/index.html',
'/administrator/components/com_dpcalendar/views/events/index.html',
'/administrator/components/com_dpcalendar/views/events/tmpl/index.html',
'/administrator/components/com_dpcalendar/views/extcalendar/index.html',
'/administrator/components/com_dpcalendar/views/extcalendar/tmpl/index.html',
'/administrator/components/com_dpcalendar/views/extcalendars/index.html',
'/administrator/components/com_dpcalendar/views/extcalendars/tmpl/index.html',
'/administrator/components/com_dpcalendar/views/index.html',
'/administrator/components/com_dpcalendar/views/location/index.html',
'/administrator/components/com_dpcalendar/views/locations/index.html',
'/administrator/components/com_dpcalendar/views/locations/tmpl/index.html',
'/administrator/components/com_dpcalendar/views/support/index.html',
'/administrator/components/com_dpcalendar/views/support/tmpl/index.html',
'/administrator/components/com_dpcalendar/views/tools/index.html',
'/administrator/components/com_dpcalendar/views/tools/tmpl/index.html',
'/media/com_dpcalendar/images/admin/48-attendee.png',
'/media/com_dpcalendar/images/admin/48-attendees.png',
'/media/com_dpcalendar/images/admin/index.html',
'/media/com_dpcalendar/images/index.html',
'/media/com_dpcalendar/images/site/index.html',
'/media/com_dpcalendar/index.html',
'/components/com_dpcalendar/controllers/attendee.php',
'/components/com_dpcalendar/controllers/index.html',
'/components/com_dpcalendar/helpers/dpcalendaricon.php',
'/components/com_dpcalendar/helpers/index.html',
'/components/com_dpcalendar/helpers/message.php',
'/components/com_dpcalendar/helpers/share.php',
'/components/com_dpcalendar/index.html',
'/components/com_dpcalendar/libraries',
'/components/com_dpcalendar/metadata.xml',
'/components/com_dpcalendar/models/forms/event.xml',
'/components/com_dpcalendar/models/forms/index.html',
'/components/com_dpcalendar/models/forms/location.xml',
'/components/com_dpcalendar/models/index.html',
'/components/com_dpcalendar/models/message.php',
'/components/com_dpcalendar/tables/index.html',
'/components/com_dpcalendar/views/attendee',
'/components/com_dpcalendar/views/calendar/index.html',
'/components/com_dpcalendar/views/calendar/tmpl/dpcalendar.css',
'/components/com_dpcalendar/views/calendar/tmpl/dpcalendar.js',
'/components/com_dpcalendar/views/calendar/tmpl/index.html',
'/components/com_dpcalendar/views/davcalendar/index.html',
'/components/com_dpcalendar/views/davcalendar/tmpl/index.html',
'/components/com_dpcalendar/views/event/index.html',
'/components/com_dpcalendar/views/event/metadata.xml',
'/components/com_dpcalendar/views/event/tmpl/default.css',
'/components/com_dpcalendar/views/event/tmpl/event.js',
'/components/com_dpcalendar/views/event/tmpl/index.html',
'/components/com_dpcalendar/views/event/tmpl/none-responsive.css',
'/components/com_dpcalendar/views/events/index.html',
'/components/com_dpcalendar/views/events/metadata.xml',
'/components/com_dpcalendar/views/events/tmpl/index.html',
'/components/com_dpcalendar/views/form/index.html',
'/components/com_dpcalendar/views/form/metadata.xml',
'/components/com_dpcalendar/views/form/tmpl/edit.css',
'/components/com_dpcalendar/views/form/tmpl/edit.js',
'/components/com_dpcalendar/views/form/tmpl/edit.php',
'/components/com_dpcalendar/views/form/tmpl/edit_date.php',
'/components/com_dpcalendar/views/form/tmpl/edit_metadata.php',
'/components/com_dpcalendar/views/form/tmpl/edit_payment.php',
'/components/com_dpcalendar/views/form/tmpl/index.html',
'/components/com_dpcalendar/views/index.html',
'/components/com_dpcalendar/views/list/index.html',
'/components/com_dpcalendar/views/list/tmpl/index.html',
'/components/com_dpcalendar/views/map/index.html',
'/components/com_dpcalendar/views/map/tmpl/index.html',
'/components/com_dpcalendar/views/map/tmpl/map.js',
'/components/com_dpcalendar/views/message',
'/components/com_dpcalendar/views/profile/index.html',
'/components/com_dpcalendar/views/profile/tmpl/default.js',
'/components/com_dpcalendar/views/profile/tmpl/index.html',
'/modules/mod_dpcalendar_counter/index.html',
'/modules/mod_dpcalendar_counter/tmpl/index.html',
'/modules/mod_dpcalendar_map/index.html',
'/modules/mod_dpcalendar_map/tmpl/index.html',
'/modules/mod_dpcalendar_map/tmpl/map.js',
'/modules/mod_dpcalendar_mini/index.html',
'/modules/mod_dpcalendar_mini/tmpl/index.html',
'/modules/mod_dpcalendar_upcoming/index.html',
'/modules/mod_dpcalendar_upcoming/tmpl/default.css',
'/modules/mod_dpcalendar_upcoming/tmpl/horizontal-1.css',
'/modules/mod_dpcalendar_upcoming/tmpl/horizontal-1.php',
'/modules/mod_dpcalendar_upcoming/tmpl/horizontal-2.css',
'/modules/mod_dpcalendar_upcoming/tmpl/horizontal-2.php',
'/modules/mod_dpcalendar_upcoming/tmpl/images',
'/modules/mod_dpcalendar_upcoming/tmpl/index.html',
'/modules/mod_dpcalendar_upcoming/tmpl/simple.css',
'/modules/mod_dpcalendar_upcoming/tmpl/vertical-1.css',
'/modules/mod_dpcalendar_upcoming/tmpl/vertical-1.php',
'/plugins/content/dpcalendar/index.html',
'/plugins/dpcalendar/caldav/dpcalendar_caldav.php',
'/plugins/dpcalendar/caldav/dpcalendar_caldav.xml',
'/plugins/dpcalendar/caldav/index.html',
'/plugins/dpcalendar/caldav/libraries/caldav/index.html',
'/plugins/dpcalendar/caldav/libraries/index.html',
'/plugins/dpcalendar/csv/dpcalendar_csv.php',
'/plugins/dpcalendar/csv/dpcalendar_csv.xml',
'/plugins/dpcalendar/csv/index.html',
'/plugins/dpcalendar/exchange/dpcalendar_exchange.php',
'/plugins/dpcalendar/exchange/dpcalendar_exchange.xml',
'/plugins/dpcalendar/exchange/index.html',
'/plugins/dpcalendar/facebook/dpcalendar_facebook.php',
'/plugins/dpcalendar/facebook/dpcalendar_facebook.xml',
'/plugins/dpcalendar/facebook/index.html',
'/plugins/dpcalendar/gcalendar',
'/plugins/dpcalendar/google/dpcalendar_google.php',
'/plugins/dpcalendar/google/dpcalendar_google.xml',
'/plugins/dpcalendar/google/index.html',
'/plugins/dpcalendar/ical/dpcalendar_ical.php',
'/plugins/dpcalendar/ical/dpcalendar_ical.xml',
'/plugins/dpcalendar/ical/index.html',
'/plugins/dpcalendar/jcalpro/dpcalendar_jcalpro.php',
'/plugins/dpcalendar/jcalpro/dpcalendar_jcalpro.xml',
'/plugins/dpcalendar/jcalpro/index.html',
'/plugins/dpcalendar/jevents/dpcalendar_jevents.php',
'/plugins/dpcalendar/jevents/dpcalendar_jevents.xml',
'/plugins/dpcalendar/jevents/index.html',
'/plugins/dpcalendar/jomsocial/dpcalendar_jomsocial.php',
'/plugins/dpcalendar/jomsocial/dpcalendar_jomsocial.xml',
'/plugins/dpcalendar/jomsocial/index.html',
'/plugins/dpcalendar/manual',
'/plugins/dpcalendar/meetup/dpcalendar_meetup.php',
'/plugins/dpcalendar/meetup/dpcalendar_meetup.xml',
'/plugins/dpcalendar/meetup/index.html',
'/plugins/dpcalendar/paypal',
'/plugins/dpcalendar/stripe',
'/plugins/dpcalendar/twitter/dpcalendar_twitter.php',
'/plugins/dpcalendar/twitter/dpcalendar_twitter.xml',
'/plugins/dpcalendar/twitter/index.html',
'/plugins/finder/dpcalendar/index.html',
'/plugins/search/dpcalendar/index.html',

// From v6.0.0 to v7.0.0
'/administrator/components/com_dpcalendar/helpers/html/datetime.php',
'/administrator/components/com_dpcalendar/libraries/dpcalendar/DPCalendar/CCL',
'/administrator/components/com_dpcalendar/libraries/dpcalendar/DPCalendar/Helper/Fullcalendar.php',
'/administrator/components/com_dpcalendar/libraries/jcomments',
'/administrator/components/com_dpcalendar/models/fields/dpcolor.php',
'/administrator/components/com_dpcalendar/models/fields/fframeworks.php',
'/administrator/components/com_dpcalendar/models/types',
'/administrator/components/com_dpcalendar/views/cpanel/tmpl/default.css',
'/administrator/components/com_dpcalendar/views/extcalendar/tmpl/edit.php',
'/administrator/components/com_dpcalendar/views/extcalendar/tmpl/edit_params.php',
'/administrator/components/com_dpcalendar/views/support',
'/media/com_dpcalendar/images/admin',
'/media/com_dpcalendar/images/site',
'/components/com_dpcalendar/controllers/locationforms.php',
'/components/com_dpcalendar/layouts/booking/form',
'/components/com_dpcalendar/layouts/calendar',
'/components/com_dpcalendar/layouts/comment',
'/components/com_dpcalendar/layouts/content',
'/components/com_dpcalendar/layouts/event/form',
'/components/com_dpcalendar/layouts/event/images.php',
'/components/com_dpcalendar/layouts/events',
'/components/com_dpcalendar/layouts/location/details.php',
'/components/com_dpcalendar/layouts/location/form',
'/components/com_dpcalendar/layouts/share',
'/components/com_dpcalendar/layouts/ticket/form',
'/components/com_dpcalendar/layouts/tickets',
'/components/com_dpcalendar/layouts/user',
'/components/com_dpcalendar/models/map.php',
'/components/com_dpcalendar/views/davcalendar/tmpl/edit.php',
'/components/com_dpcalendar/views/davcalendar/tmpl/edit_header.php',
'/components/com_dpcalendar/views/event/tmpl/default_comments.php',
'/components/com_dpcalendar/views/event/tmpl/empty.php',
'/components/com_dpcalendar/views/form/tmpl/edit.xml',
'/components/com_dpcalendar/views/list/tmpl/blog_content.php',
'/components/com_dpcalendar/views/list/tmpl/blog_footer.php',
'/components/com_dpcalendar/views/list/tmpl/default_content.php',
'/components/com_dpcalendar/views/list/tmpl/default_footer.php',
'/components/com_dpcalendar/views/locationform/tmpl/edit.xml',
'/components/com_dpcalendar/views/map/tmpl/default_content.php',
'/components/com_dpcalendar/views/map/tmpl/default_header.php',
'/modules/mod_dpcalendar_map/tmpl/default_content.php',
'/modules/mod_dpcalendar_map/tmpl/default_header.php',
'/plugins/dpcalendar/facebook/libraries',

// From v7.0.0 to v7.1.0
'/administrator/components/com_dpcalendar/models/fields/dpcategory.php',
'/administrator/components/com_dpcalendar/models/fields/dpcategoryedit.php',
'/administrator/components/com_dpcalendar/models/fields/radio.php',
'/administrator/components/com_dpcalendar/sql/updates/mysql/2.0.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/2.2.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/3.0.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/3.3.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/4.0.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/4.0.6.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/4.1.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/4.1.1.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/4.1.2.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/4.2.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/5.0.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/5.1.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/5.2.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/5.2.3.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/5.3.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/5.4.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/5.5.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/5.6.0.sql',
'/components/com_dpcalendar/views/ticketform/tmpl/default.xml',

// From v7.1.0 to v7.2.0
'/administrator/components/com_dpcalendar/helpers/filter.php',
'/administrator/components/com_dpcalendar/helpers/html',
'/administrator/components/com_dpcalendar/helpers/schema.php',
'/administrator/components/com_dpcalendar/views/bookings/tmpl/modal.php',
'/components/com_dpcalendar/views/bookingform/tmpl/default_footer.php',
'/components/com_dpcalendar/views/bookingform/tmpl/default_header.php',
'/components/com_dpcalendar/views/davcalendar/tmpl/default_header.php',
'/components/com_dpcalendar/views/form/tmpl/default_header.php',
'/components/com_dpcalendar/views/invite/tmpl/default_header.php',
'/components/com_dpcalendar/views/locationform/tmpl/default_header.php',
'/components/com_dpcalendar/views/ticketform/tmpl/default_header.php',

// From v7.2.0 to v7.3.0
'/administrator/components/com_dpcalendar/libraries/.gitignore',
'/administrator/components/com_dpcalendar/libraries/vendor',
'/administrator/components/com_dpcalendar/views/event/tmpl/default_location.php',
'/media/com_dpcalendar/images/icons/info.svg',
'/media/com_dpcalendar/scss',
'/administrator/components/com_dpcalendar/script.php',
'/components/com_dpcalendar/views/form/tmpl/default_location.php',
'/modules/mod_dpcalendar_counter/media',
'/modules/mod_dpcalendar_map/media',
'/modules/mod_dpcalendar_mini/media',
'/modules/mod_dpcalendar_upcoming/media',
'/plugins/dpcalendar/google/libraries',
'/plugins/dpcalendarpay/manual/images',
'/plugins/dpcalendarpay/paypal/images',
'/plugins/dpcalendarpay/stripe/images',
'/plugins/dpcalendarpay/stripe/media/scss',

// From v7.3.0 to v7.4.0
'/administrator/components/com_dpcalendar/vendor/braintree',
'/administrator/components/com_dpcalendar/vendor/clue',
'/administrator/components/com_dpcalendar/vendor/composer/ca-bundle',
'/administrator/components/com_dpcalendar/vendor/geoip2',
'/administrator/components/com_dpcalendar/vendor/maxmind',
'/administrator/components/com_dpcalendar/vendor/maxmind-db',
'/administrator/components/com_dpcalendar/vendor/moneyphp',
'/administrator/components/com_dpcalendar/vendor/paragonie',
'/administrator/components/com_dpcalendar/vendor/php-http',
'/administrator/components/com_dpcalendar/vendor/ralouphie',
'/administrator/components/com_dpcalendar/vendor/symfony',
'/media/com_dpcalendar/images/icons/directions-solid.svg',
'/media/com_dpcalendar/images/icons/external-link-square-alt-solid.svg',
'/media/com_dpcalendar/images/icons/info-circle-solid.svg',
'/media/com_dpcalendar/images/icons/map-marked-solid.svg',
'/media/com_dpcalendar/images/icons/sync-alt.svg',
'/media/com_dpcalendar/images/icons/trash-alt.svg',
'/components/com_dpcalendar/layouts/booking/register.php',
'/plugins/system/dpcalendar',

// From v7.4.0 to v8.0.0
'/administrator/components/com_dpcalendar/libraries/dpcalendar/DPCalendar/View/LayoutView.php',
'/administrator/components/com_dpcalendar/vendor/guzzle',
'/administrator/components/com_dpcalendar/vendor/guzzlehttp',
'/administrator/components/com_dpcalendar/vendor/omnipay',
'/components/com_dpcalendar/views/booking/tmpl/order_tickets.php',
'/components/com_dpcalendar/views/booking/tmpl/order_tickets_footer.php',
'/components/com_dpcalendar/views/bookingform/tmpl/default_new_actions.php',
'/components/com_dpcalendar/views/bookingform/tmpl/default_payment.php',
'/components/com_dpcalendar/views/bookingform/tmpl/default_terms.php',
'/components/com_dpcalendar/views/ticketform/view.raw.php',
'/plugins/dpcalendar/caldav/libraries',
'/plugins/dpcalendar/facebook/composer.json',
'/plugins/dpcalendar/facebook/composer.lock',
'/plugins/dpcalendar/google/composer.json',
'/plugins/dpcalendar/google/composer.lock',
'/plugins/dpcalendar/google/vendor',
'/plugins/dpcalendar/meetup/libraries',
'/plugins/dpcalendar/twitter/libraries',
'/plugins/dpcalendarpay/2checkout',
'/plugins/xmap/dpcalendar',

// From v8.0.0 to v8.1.0
'/administrator/components/com_dpcalendar/vendor/sabre/dav/phpstan.neon',
'/administrator/components/com_dpcalendar/vendor/sabre/vobject/phpstan.neon',
'/components/com_dpcalendar/views/calendar/view.raw.php',

// From v8.1.0 to v8.2.0
'/administrator/components/com_dpcalendar/libraries/dpcalendar/DPCalendar/Helper/HTTP.php',
'/administrator/components/com_dpcalendar/sql/updates/mysql/6.0.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/6.0.6.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/6.1.0.sql',
'/administrator/components/com_dpcalendar/sql/updates/mysql/6.2.0.sql',
'/administrator/components/com_dpcalendar/vendor/sabre/xml/phpstan.neon',
'/plugins/dpcalendar/spreadsheet/vendor/markbaker/complex/classes/Autoloader.php',
'/plugins/dpcalendar/spreadsheet/vendor/markbaker/complex/classes/Bootstrap.php',
'/plugins/dpcalendar/spreadsheet/vendor/markbaker/complex/classes/src/functions',
'/plugins/dpcalendar/spreadsheet/vendor/markbaker/complex/classes/src/operations',
'/plugins/dpcalendar/spreadsheet/vendor/markbaker/matrix/classes/src/Functions',
'/plugins/dpcalendar/spreadsheet/vendor/markbaker/matrix/classes/src/Operations',
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/locale/no',
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/DocumentGenerator.php',
'/plugins/dpcalendarpay/braintree/vendor/braintree/braintree_php/lib/Braintree/AmexExpressCheckoutCard.php',
'/plugins/dpcalendarpay/braintree/vendor/braintree/braintree_php/lib/Braintree/AndroidPayCard.php',
'/plugins/dpcalendarpay/braintree/vendor/braintree/braintree_php/lib/Braintree/MasterpassCard.php',
'/plugins/dpcalendarpay/braintree/vendor/braintree/braintree_php/lib/Braintree/Transaction/AmexExpressCheckoutCardDetails.php',
'/plugins/dpcalendarpay/braintree/vendor/braintree/braintree_php/lib/Braintree/Transaction/AndroidPayCardDetails.php',
'/plugins/dpcalendarpay/braintree/vendor/braintree/braintree_php/lib/Braintree/Transaction/MasterpassCardDetails.php',

// From v8.2.0 to v8.3.0
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods/BaseReader.php',

// From v8.3.0 to v8.4.0
'/administrator/components/com_dpcalendar/cli/notify.php',
'/administrator/components/com_dpcalendar/sql/updates/mysql/8.3.2.sql',

// From v8.4.0 to v8.5.0
'/administrator/components/com_dpcalendar/libraries/dpcalendar/DPCalendar/TCPDF',
'/administrator/components/com_dpcalendar/vendor/sabre/uri/phpstan.neon',
'/administrator/components/com_dpcalendar/vendor/tecnickcom',
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/functionlist.txt',

// From v8.5.0 to v8.6.0
'/administrator/components/com_dpcalendar/libraries/dpcalendar/DPCalendar/Booking/Stages/CreateInvoice.php',
'/administrator/components/com_dpcalendar/vendor/mustache/mustache/vendor/yaml',
'/components/com_dpcalendar/layouts/booking/invoice.php',
'/components/com_dpcalendar/views/booking/tmpl/invoice.php',

// From v8.7.0 to v8.8.0
'/administrator/components/com_dpcalendar/vendor/phenx/php-svg-lib/src/autoload.php',
'/media/com_dpcalendar/css/fullcalendar',
'/media/com_dpcalendar/css/scheduler',
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Memory.php',
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/JAMA/CholeskyDecomposition.php',
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/JAMA/EigenvalueDecomposition.php',
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/JAMA/SingularValueDecomposition.php',
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Xlfn.php',
'/plugins/dpcalendarpay/qr/vendor/endroid/qr-code/src/WritableInterface.php',
'/plugins/dpcalendarpay/qr/vendor/symfony/intl/Resources/data/languages/ha_NE.php',
'/plugins/dpcalendarpay/qr/vendor/symfony/intl/Resources/data/regions/en_GB.php',
'/plugins/dpcalendarpay/qr/vendor/symfony/intl/Resources/data/scripts/es_MX.php',
'/plugins/dpcalendarpay/qr/vendor/symfony/intl/Resources/data/timezones/en_GB.php',

// From v8.8.0 to v8.9.0
'/plugins/dpcalendar/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/JAMA',

// From v8.10.0 to v8.11.0
'/plugins/dpcalendar/spreadsheet/vendor/psr/http-factory/.pullapprove.yml',

// From v8.12.0 to case 10007
'/media/com_dpcalendar/images/icons/calendar-alt.svg',
'/media/com_dpcalendar/images/icons/cog.svg',
'/media/com_dpcalendar/images/icons/compress-alt.svg',
'/media/com_dpcalendar/images/icons/directions.svg',
'/media/com_dpcalendar/images/icons/expand-alt.svg',
'/media/com_dpcalendar/images/icons/external-link-square-alt.svg',
'/media/com_dpcalendar/images/icons/info-circle.svg',
'/media/com_dpcalendar/images/icons/map-marked-alt.svg',
'/media/com_dpcalendar/images/icons/map-marker-alt.svg',
'/media/com_dpcalendar/images/icons/money-bill-alt.svg',
'/media/com_dpcalendar/images/icons/pencil-alt.svg',
'/media/com_dpcalendar/images/icons/redo.svg',
'/media/com_dpcalendar/images/icons/search.svg',
'/media/com_dpcalendar/images/icons/sign-in-alt.svg',
'/media/com_dpcalendar/images/icons/sync.svg',
'/media/com_dpcalendar/images/icons/times.svg',

// From v8.14.0 to v8.14.1
'/modules/mod_dpcalendar_upcoming/script.php',

// From v8.14.1 to case 10168
'/plugins/system/dpcalendarytp/modules/elements/calendar/images/icon-small.svg',
'/plugins/system/dpcalendarytp/modules/elements/list/images/icon-small.svg',

// From v8.14.1 to case 10165
'/plugins/system/dpcalendarytp/modules/elements/calendar/images/icon-small.svg',
'/plugins/system/dpcalendarytp/modules/elements/list/images/icon-small.svg',

// From v8.14.1 to case 10175
'/plugins/system/dpcalendarytp/modules/elements/calendar/images/icon-small.svg',
'/plugins/system/dpcalendarytp/modules/elements/list/images/icon-small.svg',

// From v8.14.3 to update dependencies
'/administrator/components/com_dpcalendar/vendor/doctrine/deprecations/phpcs.xml',
'/administrator/components/com_dpcalendar/vendor/doctrine/deprecations/phpstan.neon',
'/plugins/dpcalendarpay/qr/vendor/symfony/intl/Resources/data/currencies/en_AE.php',
'/plugins/dpcalendarpay/qr/vendor/symfony/intl/Resources/data/currencies/en_PH.php',
'/plugins/dpcalendarpay/qr/vendor/symfony/intl/Resources/data/scripts/en_CA.php',
'/plugins/dpcalendarpay/qr/vendor/symfony/intl/Resources/data/timezones/om.php',
'/plugins/dpcalendarpay/qr/vendor/symfony/intl/Resources/data/timezones/rw.php',

// From v8.15.0 to case 10397
'/administrator/components/com_dpcalendar/libraries/dpcalendar/DPCalendar/Helper/Transifex.php',

// From v8.15.0 to case 10464
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/LICENSE',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/phpdoc.xml',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/public',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/src/Data/MaskPatternTester.php',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/src/Data/QRDataAbstract.php',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/src/Data/QRDataInterface.php',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/src/Helpers',

// From v8.16.0 to update dependencies
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/.editorconfig',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/.phan',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-qrcode/.readthedocs.yml',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-settings-container/.phan',
'/administrator/components/com_dpcalendar/vendor/chillerlan/php-settings-container/phpdoc.xml',
'/administrator/components/com_dpcalendar/vendor/phenx/php-font-lib/.htaccess',
'/administrator/components/com_dpcalendar/vendor/phenx/php-font-lib/bower.json',
'/administrator/components/com_dpcalendar/vendor/phenx/php-font-lib/index.php',
'/administrator/components/com_dpcalendar/vendor/phenx/php-font-lib/src/FontLib/Autoloader.php',

// From v8.17.1 to case 9935
'/administrator/components/com_dpcalendar/vendor/doctrine/collections/.doctrine-project.json',
];

foreach ($files as $file) {
	$fullPath = JPATH_ROOT . $file;

	if (empty($file) || !file_exists($fullPath)) {
		continue;
	}

	if (is_file($fullPath)) {
		unlink($fullPath);
		continue;
	}

	try {
		$files = new RecursiveIteratorIterator(
			new RecursiveDirectoryIterator($fullPath, RecursiveDirectoryIterator::SKIP_DOTS),
			RecursiveIteratorIterator::CHILD_FIRST
		);

		foreach ($files as $fileinfo) {
			$todo = $fileinfo->isDir() ? 'rmdir' : 'unlink';
			$todo($fileinfo->getRealPath());
		}

		rmdir($fullPath);
	} catch (Exception $e) {
	}
}
